### ISSUE TITLE
query undefined.

### ISSUE THREAD

**Issue by akash2k19** [arjunkhetia/Node.Js-Express-MySQL-Project#2]
Set up:
- Changed the database configuration in the dbconfig file. Verified that mysql connection is valid with proper login credentials, port etc.
- Ran -> nodemon bin/www

Error:
"Uncaught Exception is thrown with  TypeError: Cannot read property 'query' of undefined"
Possible reason:
pool is not created properly.

**Comment by arjunkhetia** [comment]
It's working for a proper MySQL Server configuration with connection pool.
